import { Badge } from '../types/badge.types';

export const BADGES: Badge[] = [

        // ─── Başlangıç ───────────────────────────────────────
        {
                id: 'ilk_yorum',
                emoji: '🗣️',
                icon: 'MessageCircle',
                iconColor: '#60a5fa',
                iconBg: 'rgba(96, 165, 250, 0.15)',
                name: 'Söz Vermiş',
                title: '"Susması beklenirdi"',
                description: 'İlk yorumunu yaptın.',
                group: 'baslangic',
                xpReward: 20,
                isSecret: false,
        },
        {
                id: 'ilk_gonderi',
                emoji: '📸',
                icon: 'Camera',
                iconColor: '#f472b6',
                iconBg: 'rgba(244, 114, 182, 0.15)',
                name: 'Sofra Kurdu',
                title: '"Yemek soğumadan fotoğraflanır"',
                description: 'İlk gönderini paylaştın.',
                group: 'baslangic',
                xpReward: 30,
                isSecret: false,
        },
        {
                id: 'ilk_begeni',
                emoji: '❤️',
                icon: 'Heart',
                iconColor: '#f43f5e',
                iconBg: 'rgba(244, 63, 94, 0.15)',
                name: 'Kalp Açık',
                title: '"Sevmekten ödü kopar değil"',
                description: 'İlk beğenini yaptın.',
                group: 'baslangic',
                xpReward: 10,
                isSecret: false,
        },
        {
                id: 'ilk_kayit',
                emoji: '🔖',
                icon: 'Bookmark',
                iconColor: '#a78bfa',
                iconBg: 'rgba(167, 139, 250, 0.15)',
                name: 'Depo Dolu',
                title: '"Yapacaklar listesi büyüyor"',
                description: 'İlk tarifi kaydettin.',
                group: 'baslangic',
                xpReward: 15,
                isSecret: false,
        },
        {
                id: 'profil_tamam',
                emoji: '👤',
                icon: 'UserCheck',
                iconColor: '#34d399',
                iconBg: 'rgba(52, 211, 153, 0.15)',
                name: 'Kapı Açıldı',
                title: '"Artık yüzü var"',
                description: 'Profilini %100 tamamladın.',
                group: 'baslangic',
                xpReward: 25,
                isSecret: false,
        },

        // ─── Yemek Kültürü ────────────────────────────────────
        {
                id: 'damak_atesi',
                emoji: '🌶️',
                icon: 'Flame',
                iconColor: '#f97316',
                iconBg: 'rgba(249, 115, 22, 0.15)',
                name: 'Damak Ateşi',
                title: '"Yanıyor ama devam ediyor"',
                description: 'Acı meydan okuma modunda 5 tarif yaptın.',
                group: 'yemek_kulturu',
                xpReward: 50,
                isSecret: false,
        },
        {
                id: 'lezzet_gezgini',
                emoji: '🌍',
                icon: 'Globe',
                iconColor: '#22d3ee',
                iconBg: 'rgba(34, 211, 238, 0.15)',
                name: 'Lezzet Gezgini',
                title: '"Pasaportu tariflerle dolu"',
                description: '5 farklı ülke mutfağından tarif paylaştın.',
                group: 'yemek_kulturu',
                xpReward: 60,
                isSecret: false,
        },
        {
                id: 'dede_ocagi',
                emoji: '👵',
                icon: 'BookOpen',
                iconColor: '#fb923c',
                iconBg: 'rgba(251, 146, 60, 0.15)',
                name: 'Dede Ocağı',
                title: '"Büyükannenin sırrını taşıyor"',
                description: 'Aile tarif arşivine 10 tarif ekledin.',
                group: 'yemek_kulturu',
                xpReward: 75,
                isSecret: false,
        },
        {
                id: 'gece_kusu',
                emoji: '🕛',
                icon: 'Moon',
                iconColor: '#818cf8',
                iconBg: 'rgba(129, 140, 248, 0.15)',
                name: 'Gece Kuşu',
                title: '"Saat 01:00, yine mutfakta"',
                description: 'Gece yarısı modunda 7 tarif yaptın.',
                group: 'yemek_kulturu',
                xpReward: 45,
                isSecret: true,
        },
        {
                id: 'zincir_ustasi',
                emoji: '🔗',
                icon: 'Link2',
                iconColor: '#94a3b8',
                iconBg: 'rgba(148, 163, 184, 0.15)',
                name: 'Zincir Ustası',
                title: '"Bir tarif bin el dolaştı"',
                description: 'Başlattığın tarif zinciri 10 halkaya ulaştı.',
                group: 'yemek_kulturu',
                xpReward: 80,
                isSecret: false,
        },

        // ─── Sosyal ──────────────────────────────────────────
        {
                id: 'mahalle_bakkali',
                emoji: '🎙️',
                icon: 'Mic2',
                iconColor: '#e879f9',
                iconBg: 'rgba(232, 121, 249, 0.15)',
                name: 'Mahalle Bakkalı',
                title: '"Herkesin bir lafı var"',
                description: 'Toplam 50 yorum yaptın.',
                group: 'sosyal',
                xpReward: 55,
                isSecret: false,
        },
        {
                id: 'el_uzatmis',
                emoji: '🤝',
                icon: 'Users',
                iconColor: '#4ade80',
                iconBg: 'rgba(74, 222, 128, 0.15)',
                name: 'El Uzatmış',
                title: '"Sofra geniş tutulur"',
                description: '20 kişiyi takip ettin.',
                group: 'sosyal',
                xpReward: 30,
                isSecret: false,
        },
        {
                id: 'duyurdum_sana',
                emoji: '📣',
                icon: 'Megaphone',
                iconColor: '#fbbf24',
                iconBg: 'rgba(251, 191, 36, 0.15)',
                name: 'Duyurdum Sana',
                title: '"Söyledim, oldu"',
                description: 'Bir gönderin 100 beğeni aldı.',
                group: 'sosyal',
                xpReward: 70,
                isSecret: false,
        },
        {
                id: 'cirak_mezun',
                emoji: '🏅',
                icon: 'GraduationCap',
                iconColor: '#14854A',
                iconBg: 'rgba(20, 133, 74, 0.15)',
                name: 'Çırak Mezun Etti',
                title: '"Ustanın izi tarifde kalır"',
                description: 'Usta olarak 3 çırağını mezun ettin.',
                group: 'sosyal',
                xpReward: 100,
                isSecret: false,
        },
        {
                id: 'trend_kiran',
                emoji: '🔥',
                icon: 'TrendingUp',
                iconColor: '#f43f5e',
                iconBg: 'rgba(244, 63, 94, 0.15)',
                name: 'Trend Kıran',
                title: '"Öyle bir şey yaptı ki..."',
                description: 'Bir gönderin keşfet sayfasına çıktı.',
                group: 'sosyal',
                xpReward: 90,
                isSecret: true,
        },

        // ─── Ustalık ─────────────────────────────────────────
        {
                id: 'hiz_sefi',
                emoji: '⚡',
                icon: 'Zap',
                iconColor: '#facc15',
                iconBg: 'rgba(250, 204, 21, 0.15)',
                name: 'Hız Şefi',
                title: '"Her gün bir tarif, hiç bahane yok"',
                description: '30 gün içinde 30 tarif paylaştın.',
                group: 'ustalik',
                xpReward: 120,
                isSecret: false,
        },
        {
                id: 'devamli_ates',
                emoji: '📅',
                icon: 'CalendarCheck',
                iconColor: '#38bdf8',
                iconBg: 'rgba(56, 189, 248, 0.15)',
                name: 'Devamlı Ateş',
                title: '"Tutarlılık bir yetenektir"',
                description: '7 hafta üst üste haftalık görevi tamamladın.',
                group: 'ustalik',
                xpReward: 150,
                isSecret: false,
        },
        {
                id: 'dolap_dedektifi',
                emoji: '🧬',
                icon: 'Search',
                iconColor: '#a78bfa',
                iconBg: 'rgba(167, 139, 250, 0.15)',
                name: 'Dolap Dedektifi',
                title: '"Buzdolabında hep bir şeyler bulur"',
                description: "Malzeme DNA'sını 15 kez kullandın.",
                group: 'ustalik',
                xpReward: 65,
                isSecret: false,
        },
        {
                id: 'yayinci_ruh',
                emoji: '🎬',
                icon: 'Video',
                iconColor: '#f472b6',
                iconBg: 'rgba(244, 114, 182, 0.15)',
                name: 'Yayıncı Ruh',
                title: '"Kamera açık, ocak yanık"',
                description: '5 canlı pişirme maratonu yaptın.',
                group: 'ustalik',
                xpReward: 85,
                isSecret: false,
        },
        {
                id: 'soframin_efendisi',
                emoji: '👑',
                icon: 'Crown',
                iconColor: '#f59e0b',
                iconBg: 'rgba(245, 158, 11, 0.2)',
                name: 'Sofranın Efendisi',
                title: '"Bu unvan hak edilir, verilmez"',
                description: "Level 10'a ulaştın.",
                group: 'ustalik',
                xpReward: 200,
                isSecret: false,
        },
];

export const getBadgeById = (id: string): Badge | undefined =>
        BADGES.find(b => b.id === id);

export const getBadgesByGroup = (group: Badge['group']): Badge[] =>
        BADGES.filter(b => b.group === group);

export const BADGE_GROUP_LABELS: Record<string, string> = {
        baslangic: 'Başlangıç',
        yemek_kulturu: 'Yemek Kültürü',
        sosyal: 'Sosyal',
        ustalik: 'Ustalık',
};
