import { Badge } from '../types/badge.types';

export const BADGES: Badge[] = [

    // ─── Başlangıç ───────────────────────────────────────
    {
        id: 'ilk_yorum',
        emoji: '🗣️',
        name: 'Söz Vermiş',
        title: '"Susması beklenirdi"',
        description: 'İlk yorumunu yaptın.',
        group: 'baslangic',
        xpReward: 20,
        isSecret: false,
    },
    {
        id: 'ilk_gonderi',
        emoji: '📸',
        name: 'Sofra Kurdu',
        title: '"Yemek soğumadan fotoğraflanır"',
        description: 'İlk gönderini paylaştın.',
        group: 'baslangic',
        xpReward: 30,
        isSecret: false,
    },
    {
        id: 'ilk_begeni',
        emoji: '❤️',
        name: 'Kalp Açık',
        title: '"Sevmekten ödü kopar değil"',
        description: 'İlk beğenini yaptın.',
        group: 'baslangic',
        xpReward: 10,
        isSecret: false,
    },
    {
        id: 'ilk_kayit',
        emoji: '🔖',
        name: 'Depo Dolu',
        title: '"Yapacaklar listesi büyüyor"',
        description: 'İlk tarifi kaydettin.',
        group: 'baslangic',
        xpReward: 15,
        isSecret: false,
    },
    {
        id: 'profil_tamam',
        emoji: '👤',
        name: 'Kapı Açıldı',
        title: '"Artık yüzü var"',
        description: 'Profilini %100 tamamladın.',
        group: 'baslangic',
        xpReward: 25,
        isSecret: false,
    },

    // ─── Yemek Kültürü ────────────────────────────────────
    {
        id: 'damak_atesi',
        emoji: '🌶️',
        name: 'Damak Ateşi',
        title: '"Yanıyor ama devam ediyor"',
        description: 'Acı meydan okuma modunda 5 tarif yaptın.',
        group: 'yemek_kulturu',
        xpReward: 50,
        isSecret: false,
    },
    {
        id: 'lezzet_gezgini',
        emoji: '🌍',
        name: 'Lezzet Gezgini',
        title: '"Pasaportu tariflerle dolu"',
        description: '5 farklı ülke mutfağından tarif paylaştın.',
        group: 'yemek_kulturu',
        xpReward: 60,
        isSecret: false,
    },
    {
        id: 'dede_ocagi',
        emoji: '👵',
        name: 'Dede Ocağı',
        title: '"Büyükannenin sırrını taşıyor"',
        description: 'Aile tarif arşivine 10 tarif ekledin.',
        group: 'yemek_kulturu',
        xpReward: 75,
        isSecret: false,
    },
    {
        id: 'gece_kusu',
        emoji: '🕛',
        name: 'Gece Kuşu',
        title: '"Saat 01:00, yine mutfakta"',
        description: 'Gece yarısı modunda 7 tarif yaptın.',
        group: 'yemek_kulturu',
        xpReward: 45,
        isSecret: true,   // Sürpriz rozet — kazanılana kadar görünmez
    },
    {
        id: 'zincir_ustasi',
        emoji: '🔗',
        name: 'Zincir Ustası',
        title: '"Bir tarif bin el dolaştı"',
        description: 'Başlattığın tarif zinciri 10 halkaya ulaştı.',
        group: 'yemek_kulturu',
        xpReward: 80,
        isSecret: false,
    },

    // ─── Sosyal ──────────────────────────────────────────
    {
        id: 'mahalle_bakkali',
        emoji: '🎙️',
        name: 'Mahalle Bakkalı',
        title: '"Herkesin bir lafı var"',
        description: 'Toplam 50 yorum yaptın.',
        group: 'sosyal',
        xpReward: 55,
        isSecret: false,
    },
    {
        id: 'el_uzatmis',
        emoji: '🤝',
        name: 'El Uzatmış',
        title: '"Sofra geniş tutulur"',
        description: '20 kişiyi takip ettin.',
        group: 'sosyal',
        xpReward: 30,
        isSecret: false,
    },
    {
        id: 'duyurdum_sana',
        emoji: '📣',
        name: 'Duyurdum Sana',
        title: '"Söyledim, oldu"',
        description: 'Bir gönderin 100 beğeni aldı.',
        group: 'sosyal',
        xpReward: 70,
        isSecret: false,
    },
    {
        id: 'cirak_mezun',
        emoji: '🏅',
        name: 'Çırak Mezun Etti',
        title: '"Ustanın izi tarifde kalır"',
        description: 'Usta olarak 3 çırağını mezun ettin.',
        group: 'sosyal',
        xpReward: 100,
        isSecret: false,
    },
    {
        id: 'trend_kiran',
        emoji: '🔥',
        name: 'Trend Kıran',
        title: '"Öyle bir şey yaptı ki..."',
        description: 'Bir gönderin keşfet sayfasına çıktı.',
        group: 'sosyal',
        xpReward: 90,
        isSecret: true,   // Sürpriz rozet
    },

    // ─── Ustalık ─────────────────────────────────────────
    {
        id: 'hiz_sefi',
        emoji: '⚡',
        name: 'Hız Şefi',
        title: '"Her gün bir tarif, hiç bahane yok"',
        description: '30 gün içinde 30 tarif paylaştın.',
        group: 'ustalik',
        xpReward: 120,
        isSecret: false,
    },
    {
        id: 'devamli_ates',
        emoji: '📅',
        name: 'Devamlı Ateş',
        title: '"Tutarlılık bir yetenektir"',
        description: '7 hafta üst üste haftalık görevi tamamladın.',
        group: 'ustalik',
        xpReward: 150,
        isSecret: false,
    },
    {
        id: 'dolap_dedektifi',
        emoji: '🧬',
        name: 'Dolap Dedektifi',
        title: '"Buzdolabında hep bir şeyler bulur"',
        description: 'Malzeme DNA\'sını 15 kez kullandın.',
        group: 'ustalik',
        xpReward: 65,
        isSecret: false,
    },
    {
        id: 'yayinci_ruh',
        emoji: '🎬',
        name: 'Yayıncı Ruh',
        title: '"Kamera açık, ocak yanık"',
        description: '5 canlı pişirme maratonu yaptın.',
        group: 'ustalik',
        xpReward: 85,
        isSecret: false,
    },
    {
        id: 'soframin_efendisi',
        emoji: '👑',
        name: 'Sofranın Efendisi',
        title: '"Bu unvan hak edilir, verilmez"',
        description: 'Level 10\'a ulaştın.',
        group: 'ustalik',
        xpReward: 200,
        isSecret: false,
    },
];

export const getBadgeById = (id: string): Badge | undefined =>
    BADGES.find(b => b.id === id);

export const getBadgesByGroup = (group: Badge['group']): Badge[] =>
    BADGES.filter(b => b.group === group);

export const BADGE_GROUP_LABELS: Record<string, string> = {
    baslangic: 'Başlangıç',
    yemek_kulturu: 'Yemek Kültürü',
    sosyal: 'Sosyal',
    ustalik: 'Ustalık',
};
